sudo: false

language: cpp

cache:
  directories:
    - downloads

os:
  - osx

# Only build the master branch, otherwise once the release is added, Github
# creates a tag which triggers another identical build.
branches:
  only:
    - master

before_install:
  - brew update

install:
  - ls
  - if [ ! -d /Users/travis/downloads ] ; then
      mkdir /Users/travis/downloads
    fi;
  - pushd /Users/travis/downloads
  - if [ ! -f clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz ] ; then
      curl -L -O http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz;
    fi
  - tar -xf clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz;
  - mv clang+llvm-3.9.0-x86_64-apple-darwin /usr/local/llvm39;
  - chmod 744 /usr/local/llvm39;
  - popd;
  - ls /usr/local/llvm39;
  - ls /usr/local/llvm39/bin;
  - brew unlink boost
  - brew install openssl
  - brew install cmake

script:
  - BOOSTVER=1.62.0
  - PYTHONVER=3.5.2
  - OSXVER=$(sw_vers -productVersion)
  # Build python3 with clang3.9
  - pushd /Users/travis/downloads
  - brew unpack --patch --destdir=. python3
  - pushd python3-$PYTHONVER;
  - if [ ! -d /usr/local/Cellar/python3 ] ; then
      mkdir /usr/local/Cellar/python3 ;
    fi
  - if [ ! -d /usr/local/Cellar/python3/$PYTHONVER ] ; then
      mkdir /usr/local/Cellar/python3/$PYTHONVER ;
    fi
  - ./configure --prefix=/usr/local/Cellar/python3/$PYTHONVER --enable-ipv6 --datarootdir=/usr/local/Cellar/python3/$PYTHONVER/share --datadir=/usr/local/Cellar/python3/$PYTHONVER/share --enable-shared --with-ensurepip --without-gcc CC=/usr/local/llvm39/bin/clang CXX=/usr/local/llvm39/bin/clang++ LDFLAGS="$MACOS_SDK -L/usr/local/opt/openssl/lib" CPPFLAGS="-pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/openssl/include $MACOS_SDK" CFLAGS="-pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/openssl/include $MACOS_SDK" MACOSX_DEPLOYMENT_TARGET=$OSXVER;
  - CC=/usr/local/llvm39/bin/clang;
  - CXX=/usr/local/llvm39/bin/clang++;
  - LDFLAGS="$MACOS_SDK -L/usr/local/opt/openssl/lib";
  - CPPFLAGS="-pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/openssl/include $MACOS_SDK" ;
  - CFLAGS="-pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/openssl/include $MACOS_SDK";
  - MACOSX_DEPLOYMENT_TARGET=$OSXVER;
  - make;
  - make install PYTHONAPPSDIR=/usr/local/Cellar/python3/$PYTHONVER;
  - popd; popd;
  - brew link --overwrite python3
  - brew bottle python3

before_deploy:
  - export RELEASE_FILES=$(ls *.bottle.tar.gz)
  - "echo 'Deploying files to Github: '$RELEASE_FILES"

deploy:
  provider: releases
  api_key:
    secure: "OB0ausYntt4yWPIUooQbKD2okR7w4EyLctvxva/n3MVapLWiNyFVqLbyBW9gJNOeq7k7X7zN9H59rqXJ7wKCxlPjKxFXmNvfqPYOcRj34tLcInv6AFUXIT5mYFpaJTLpG7r4wA3kOiHIeozSoIgb7evOId6bAR8JcLbSlqgFqPJrvDfKxo+IzNVykSQiyIqjTAgt3L92c6gfLy7qENkhcjtxCh79OejVR1gbDyPNlo9Rmp3B1tIc0nnFM154MFJ50ZkKMnmXfx/9MG6difhrcCUZtHuMN+8aXar7yGoUCuqcUJkpbi2NtDTI61ogXGOp/twS1kjUAW3UCqAsj4/yF9vGCAaWI9iL4nL/N3Q9v3PcthjEtOXACIXL3TI/KhxhMU+47yerx9UqqtCn0nnYPpdd9FtT1oEVbRVca3TQ84L9AoHkqVFSUmjJ20a0OK9tLdi57AvLbXdhB6Q3g3DW/8XTp042x4yaZxeCLw9qcK/2Q3rWI+1MBAQeVI3C2/xs25/NSotFAlq3p1nIPrq6ZuhClH1GOMIheS5+19SLNn9FPoWoTUz5AIYW3Xe0+9vyEBHzJKhMB9fF3ahfduFbsRALt7NQCjSH38F6v0pqtYMe65eQIUpNXfdT5RdMZloQxSPOvnNU6ElaWXOc6lIalTGZ5Fdp3sV+QhNeYeAcvQU="
  file: "${RELEASE_FILES}"
  skip_cleanup: true
  on:
    repo: uclatommy/travis-homebrew-bottle
  overwrite: true
