sudo: false

matrix:
  fast_finish: true
  include:
    - language: cpp
      os: osx
      osx_image: xcode8
    - language: cpp
      os: osx
      osx_image: xcode7

cache:
  directories:
  - downloads

# Only build the master branch, otherwise once the release is added, Github
# creates a tag which triggers another identical build.
branches:
  only:
    - master

before_install:
  - brew update
  - OSXVER=$(sw_vers -productVersion | awk -F '.' '{print $1 "." $2}')
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [ $OSXVER == 10.10 ] ; then
        wget 'https://github.com/uclatommy/travis-homebrew-bottle/releases/download/quantum-dev/hdf5-1.8.17.yosemite.bottle.tar.gz';
        wget 'https://github.com/uclatommy/travis-homebrew-bottle/releases/download/quantum-dev/python3-3.5.2_3.yosemite.bottle.1.tar.gz';
        wget 'https://github.com/uclatommy/travis-homebrew-bottle/releases/download/quantum-dev/valgrind-3.12.0.yosemite.bottle.1.tar.gz';
        brew install *.yosemite.bottle*tar.gz;
      elif [ $OSXVER == 10.11 ] ; then
        wget 'https://github.com/uclatommy/travis-homebrew-bottle/releases/download/quantum-dev/hdf5-1.8.17.el_capitan.bottle.tar.gz';
        wget 'https://github.com/uclatommy/travis-homebrew-bottle/releases/download/quantum-dev/python3-3.5.2_3.el_capitan.bottle.1.tar.gz';
        wget 'https://github.com/uclatommy/travis-homebrew-bottle/releases/download/quantum-dev/valgrind-3.12.0.el_capitan.bottle.1.tar.gz';
        brew install *.el_capitan.bottle*tar.gz;
      fi
    fi

install:
  - if [ ! -d downloads ] ; then
      mkdir downloads ;
    fi;
  - pushd downloads
  - ls -l
  - if [ ! -f clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz ] ; then
      curl -L -O http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz;
    fi;
  - if [ -d /usr/local/llvm39 ] ; then
      rm -r /usr/local/llvm39;
    fi
  - if [ -d clang+llvm-3.9.0-x86_64-apple-darwin ] ; then
      rm -r clang+llvm-3.9.0-x86_64-apple-darwin;
    fi
  - tar -xf clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz;
  - mv clang+llvm-3.9.0-x86_64-apple-darwin /usr/local/llvm39;
  - chmod 744 /usr/local/llvm39;
  - export CC=/usr/local/llvm39/bin/clang
  - export CXX=/usr/local/llvm39/bin/clang++
  - brew unlink boost
  - if [ ! -f boost-1.62.0.*.bottle*tar.gz ]; then
      travis_wait 30 brew install --build-bottle boost;
      brew install --build-bottle boost-python;
      brew bottle boost;
      brew bottle boost-python;
    else
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        if [ $OSXVER == 10.10 ] ; then
          brew install *.yosemite.bottle*tar.gz;
        elif [ $OSXVER == 10.11 ] ; then
          brew install *.el_capitan.bottle*tar.gz;
        fi
      fi
    fi
  - popd;

script:
  - BOOSTVER=1.62.0
  - PYTHONVER=3.5.2
  - OSXVER=$(sw_vers -productVersion | awk -F '.' '{print $1 "." $2}')
  - VALGRIND=3.12.0
  - HDF5=1.8.17
  - MACOS_SDK="-mmacosx-version-min=$OSXVER";
  - pushd downloads
# Build Boost
  - travis_wait 30 ./../build-boost.sh $OSXVER $PYTHONVER $BOOSTVER
# Build Boost-Python
  - ./../build-boost-python.sh $OSXVER $PYTHONVER $BOOSTVER
# Make bottles
  - popd
  - mkdir bottles-osx$OSXVER && pushd bottles-osx$OSXVER
  - brew bottle boost
  - brew bottle boost-python
  - popd

before_deploy:
  - export RELEASE_FILES=$(ls bottles-osx$OSXVER)
  - "echo 'Deploying files to Github: '$RELEASE_FILES"

deploy:
  provider: releases
  api_key:
    secure: "TqfrKR8qj8WNPcHvo6b9BhJmAYO0LEh8CI95UJ8W9RizWmiQPeq05nDyIoKW2gHvtgHmDnAWXr5je40yrQWq64EyogfaG+0gfJfdVV2cZcuJ4MSLW7sgEWwRaybHeKJjZTKVjrTA2EZDba3czYNclILbP+m1aq0nCzl37/+DdTkbGfkhxUcD7sBoPEYvAJWnOptKfsmOTwNE8bymnf4MutiI8H/8PQoj+SFJfLmGgfKU4PAVtE4CuY6Y9wZXsDv6jxSbIJxRhyY3Jki0npQ8tgv1iUQhc0W9OmFTEQ8AvdqHTaCF10F6CKwfGQWsEZyEbcqSy7ZzoFCuCTBM62u7z4EyXHSoeaK70Z2DWLfbiByOVB/Fg4t41y3JSgP/JUJY919gHi7FO/PBVuM8JwTxqkMqDvFiMhDi0hGwxZuJPb/NUJBBBK6jBfPpkWTlOIkVFET23WtE0+0TKoeeFZVFdJtPI0JlOCnmgjfvMgiUYt/JqKJvhBPa1iTu7iZKQp58NuuzLXn27yZrw2TaIOeH4Vnqz1Sf7JUL+IL8AHYeH/AtYNRCaKvvmDiVzSLL4zKzSQTde4ovWEPrExUUkRRCe26V0uJBosptEq7YftCoiLFDe1yEGRP1oK9K8h6hDHPxfaKTObGgA4tvzXgmSDm/Itanqpn62ChFHYPmowKpLWA="
  file: bottles-osx$OSXVER/*.gz
  file_glob: true
  skip_cleanup: true
  on:
    tag: true
  overwrite: true
